local M = {}

function M.highlight(palette, opts)
    return {
        ['@annotation'] = { fg = palette.white },
        ['@attribute'] = { fg = palette.white },
        ['@boolean'] = { fg = palette.keywords },
        ['@character'] = { fg = palette.green },
        ['@comment'] = { link = 'Comment' },
        ['@comment.documentation'] = { fg = palette.medium_gray },
        ['@comment.error'] = { fg = palette.error },
        ['@comment.note'] = { fg = palette.light_gray },
        ['@comment.todo'] = { fg = palette.todo },
        ['@comment.warning'] = { fg = palette.warning },
        ['@const.builtin'] = { fg = palette.red },
        ['@const.macro'] = { fg = palette.cyan },
        ['@constant'] = { fg = palette.white },
        ['@constructor'] = { fg = palette.keywords },
        ['@constructor.lua'] = { link = '@punctuation.bracket' },
        ['@diff.delta'] = {
            fg = palette.gray_blue,
            bg = palette.accent_blue,
            bold = true,
        },
        ['@error'] = { fg = palette.error },
        ['@function'] = vim.tbl_extend('force', { fg = palette.functions }, opts.styles.functions),
        ['@function.builtin'] = { fg = palette.functions },
        ['@function.macro'] = { fg = palette.functions },
        ['@function.method'] = { fg = palette.functions },
        ['@function.method.call'] = { fg = palette.functions },
        ['@keyword'] = vim.tbl_extend('force', { fg = palette.keywords }, opts.styles.keywords),
        ['@keyword.return'] = { fg = palette.keywords2 },
        ['@keyword.conditional'] = { fg = palette.keywords2 },
        ['@keyword.conditional.ternary'] = { fg = palette.keywords },
        ['@keyword.coroutine'] = { fg = palette.keywords },
        -- ['@keyword.exception'] = { fg = palette.red },
        ['@keyword.exception'] = { fg = palette.keywords },
        ['@keyword.function'] = vim.tbl_extend('force', { fg = palette.keywords }, opts.styles.keywords),
        ['@keyword.import'] = { fg = palette.keywords2 },
        -- ['@keyword.import'] = { fg = palette.red },
        ['@keyword.operator'] = { fg = palette.gray_blue },
        ['@keyword.repeat'] = { fg = palette.keywords2 },
        ['@label'] = { fg = palette.white },
        ['@lsp.type.comment'] = {},
        ['@markup'] = { fg = palette.fg },
        ['@markup.italic'] = { italic = true },
        ['@markup.link'] = { fg = palette.medium_gray_blue },
        ['@markup.list'] = { fg = palette.fg },
        ['@markup.list.unchecked'] = { fg = palette.fg },
        ['@markup.literal'] = { fg = palette.medium_gray },
        ['@markup.strong'] = { fg = palette.medium_gray },
        ['@markup.title'] = { fg = palette.medium_gray },
        ['@markup.underline'] = { underline = true },
        ['@module'] = { fg = palette.white },
        ['@number'] = { fg = palette.numbers },
        ['@number.float'] = { fg = palette.numbers },
        ['@operator'] = { fg = palette.medium_gray },
        ['@property'] = { fg = palette.white },
        ['@punctuation.bracket'] = { fg = palette.medium_gray },
        ['@punctuation.delimiter'] = { fg = palette.medium_gray },
        ['@string'] = { fg = palette.strings },
        ['@string.escape'] = { fg = palette.strings },
        ['@string.regexp'] = { fg = palette.strings },
        ['@string.special.path'] = { fg = palette.light_gray },
        ['@string.special.symbol'] = { fg = palette.medium_gray },
        ['@property.class.css'] = { fg = palette.light_blue },
        ['@markup.heading'] = { fg = palette.fg },
        ['@tag'] = { fg = palette.keywords },
        -- ['@tag.attribute'] = { fg = palette.light_gray },
        ['@tag.attribute'] = { fg = palette.light_blue },
        ['@tag.delimiter'] = { fg = palette.medium_gray },
        ['@text.uri'] = { fg = palette.light_gray },
        ['@type'] = vim.tbl_extend('force', { fg = palette.types }, opts.styles.type),
        ['@type.builtin'] = { fg = palette.types },
        ['@variable'] = vim.tbl_extend('force', { fg = palette.white }, opts.styles.variables),
        ['@variable.builtin'] = { fg = palette.keywords },
        ['@variable.field'] = { fg = palette.white },
        ['@variable.parameter'] = { fg = palette.white },
        ['@variable.parameter.reference'] = { fg = palette.white },
    }
end

return M
